### PR TITLE
Legend 

### PR DESCRIPTION
**Pull request by sanandrea**
I have extended your awesome PNChart to create also a legend. Actually I have implemented the legend for Line and Pie chart. 
Added some mini customization to Pie Chart like absolute values and no description (because they appear on legend).

Thanks

### CODE REVIEW

**Comment by sanandrea** [comment]
ios simulator screen shot 02 mar 2015 09 59 26
ios simulator screen shot 02 mar 2015 09 59 36
ios simulator screen shot 02 mar 2015 09 59 39

**Comment by kevinzhow** [comment]
Hi @sanandrea , Pie chart has just been improved.
please update your code to fix the conflicts

**Comment by sanandrea** [comment]
I have solved the merge conflicts of latest improvements

**Comment by ZhangHang** [comment]
Cool

**Pull request merged**
