### PR TITLE
Fix warning in block declaration from UICountingLabel

### PR DESCRIPTION
**Pull request by 0mega**
This PR updates UICountingLabel dependency to the latest version to remove the warning of block declaration. More info [here](https://github.com/dataxpress/UICountingLabel/pull/55).

- [x] Update CocoaPods to 1.3.1
- [x] Bump target to iOS 7.0 to be able to use latest UICountingLabel
- [x] Update UICountingLabel to v1.4.1
- [x] Hide 'Animations' label on Scatter Chart demo

### CODE REVIEW

**Comment by 0mega** [comment]
@kevinzhow Thanks for the amazing lib, can you please review and merge if looks good, happy to address any comments.

**Comment by 0mega** [comment]
Hi @kevinzhow, sorry for pinging you again but do you have an idea of when you could review this?

**Comment by 0mega** [comment]
@kevinzhow All conflicts resolved and CI is green, please 👀

**Comment by ecaselles** [comment]
Looks good to me! @kevinzhow let's 🚀 it 🙏

**Pull request merged**
