### PR TITLE
PNChart: fix positions of xLabel, xSeparator and lines

### PR DESCRIPTION
**Pull request by ZengSir**
These items is not in the right position when add more datas. The same
situation will happen in change the PNChart’s frame.

### CODE REVIEW

**Comment by joint-song** [comment]
@kevinzhow 可以处理下PR么？

**Comment by evenluo** [comment]
@kevinzhow pr麻烦处理一下？

**Comment by kevinzhow** [comment]
@ZengSir Hi this pr was conflicted with current master, could you please help to fix it?
@evenluo @joint-song

**Comment by evenluo** [comment]
我主要遇到的是x轴有偏移的问题，我在[issue #399](https://github.com/kevinzhow/PNChart/issues/399)     中有提到我的解决办法。这个原作者 @ZengSir  能否解释一下xSeparator and lines会有什么问题么？

**Pull request closed without merging**
